import pandas as pd
import mysql.connector
from getpass import getpass

password = getpass("Enter your MySQL password: ")

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password=password,
    database="retailiq"
)

cursor = connection.cursor()

# Load CSV files
sales_data = pd.read_csv("data/sales.csv")
products_data = pd.read_csv("data/products.csv")

try:
    # -----------------------------------
    # LOAD PRODUCTS
    # -----------------------------------

    # Get products that already exist in MySQL
    cursor.execute("SELECT ProductID, Product FROM products")

    product_lookup = {
        product: product_id
        for product_id, product in cursor.fetchall()
    }

    products_added = 0

    # Insert only new products
    for index, row in products_data.iterrows():

        product_name = row["Product"]

        if product_name not in product_lookup:

            products_insert_query = """
            INSERT INTO products (Product, Category)
            VALUES (%s, %s)
            """

            cursor.execute(
                products_insert_query,
                (
                    product_name,
                    row["Category"]
                )
            )

            # Get the ProductID generated by MySQL
            product_lookup[product_name] = cursor.lastrowid

            products_added += 1

    # -----------------------------------
    # LOAD SALES TRANSACTIONS
    # -----------------------------------

    # Get TransactionIDs already loaded
    cursor.execute("SELECT TransactionID FROM sales")

    existing_transactions = {
        transaction_id
        for (transaction_id,) in cursor.fetchall()
    }

    sales_added = 0
    sales_skipped = 0

    sales_insert_query = """
    INSERT INTO sales (
        TransactionID,
        TransactionDate,
        ProductID,
        Quantity,
        Price
    )
    VALUES (%s, %s, %s, %s, %s)
    """

    for index, row in sales_data.iterrows():

        transaction_id = row["TransactionID"]

        # Skip transactions already loaded
        if transaction_id in existing_transactions:
            sales_skipped += 1
            continue

        product_id = product_lookup[row["Product"]]

        cursor.execute(
            sales_insert_query,
            (
                transaction_id,
                row["TransactionDate"],
                product_id,
                row["Quantity"],
                row["Price"]
            )
        )

        existing_transactions.add(transaction_id)
        sales_added += 1

    # Save all changes
    connection.commit()

    print("RetailIQ incremental load completed successfully!")
    print(f"New products added: {products_added}")
    print(f"New sales transactions added: {sales_added}")
    print(f"Existing transactions skipped: {sales_skipped}")

except Exception as error:

    # Undo this run if anything fails
    connection.rollback()

    print("An error occurred while loading the data.")
    print(error)

finally:

    cursor.close()
    connection.close()

    print("Database connection closed.")